version: '3.7'

services:

  vobe:
    image: vobe
    container_name: vobe_node
    build: .
    restart: always
    ports:
      - 7070:${web_port}
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./vobe/:/vobe
      - .:/home/node/app
  mongo:
    image: mongo
    container_name: vobe_mongo
    restart: always
    ports:
      - "27017:27017"

  web:
    image: nginx:mainline-alpine
    container_name: vobe_web
    ports:
      - 80:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - vobe
