version: '3'

services:

  vobe:
    build: ./
    image: vobe
    restart: always
    container_name: vobe_node
    depends_on:
      - mongo
    ports:
      - "80:${web_port}"

  mongo:
    image: mongo
    container_name: vobe_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongo_user}
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_password}