version: '3.7'

services:

  vobe:
    image: vobe
    container_name: vobe_node
    build: .
    restart: always
    ports:
      - 80:${web_port}
    links:
      - mongo
    volumes:
      - ./vobe/:/vobe

  mongo:
    image: mongo
    container_name: ${mongo_container}
    restart: always
    ports:
      - "27017:27017"