version: '3'

services:

  vobe:
    build: ./
    image: comesa/vobe
    restart: always
    container_name: vobe
    depends_on:
      - mongo
    ports:
      - "80:${PORT}"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongo_user}
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_password}