version: '3.7'

services:

  vobe:
    image: vobe
    container_name: vobe_node
    build: .
    restart: always
    environment:
      LETSENCRYPT_EMAIL: timoaeckerle@gmx.de
      LETSENCRYPT_HOST: vobe.io
      VIRTUAL_HOST: vobe.io
      VIRTUAL_PORT: 80
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./vobe/:/vobe
      - .:/home/node/app
  mongo:
    image: mongo
    container_name: vobe_mongo
    restart: always
    ports:
      - "27017:27017"

  proxy:
    image: jwilder/nginx-proxy
    container_name: vobe_proxy
    restart: unless-stopped
    volumes:
    - ./data/certs:/etc/nginx/certs
    - ./conf:/etc/nginx/conf.data
    - ./dhparam:/etc/nginx/dhparam
    - ./data/vhosts:/etc/nginx/vhost.data
    - ./data/html:/usr/share/nginx/html
    - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - 80:80
      - 443:443
    environment:
      DEFAULT_HOST: vobe.io
      DEFAULT_EMAIL: timoaeckerle@gmx.de

  ssl_provider:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    depends_on:
      - proxy
    volumes:
      - ./data/certs:/etc/nginx/certs:rw
      - ./conf:/etc/nginx/conf.d
      - ./dhparam:/etc/nginx/dhparam
      - ./data/vhosts:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro